### ISSUE TITLE
Crash when sending video resume

### ISSUE THREAD

**Issue by rubensousa** [at-internet/atinternet-android-sdk#13]
We're getting this exception when a video is resumed after being paused:

```java
Non-fatal Exception: java.lang.IllegalArgumentException
       at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:583)
       at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleWithFixedDelay(Executors.java:654)
       at com.atinternet.tracker.RichMedia.processSendPlayWithRefresh(RichMedia.java:436)
       at com.atinternet.tracker.RichMedia.sendResume(RichMedia.java:363)
```

Here's the issue:

```java
// Démarrage du refresh avec le premier intervalle
int rd = refreshDurationsSparseIntArray.valueAt(currentRefreshDurationsSparseArrayIndex);
refreshHandler = scheduler.scheduleWithFixedDelay(refreshRunnable, rd, rd, TimeUnit.SECONDS);
```
currentRefreshDurationsSparseArrayIndex points to an invalid index for some reason

We have more than 42.000 non-fatal errors on all devices and had to wrap sendResume inside a try catch block to avoid crashing the app.

**Comment by rubensousa** [comment]
Another question: Why isn't refreshDurationsSparseIntArray inside RichMedia initialized in the constructor?

**Comment by nsagnett** [comment]
Can you share code using it ?

**Comment by nsagnett** [comment]
Hi 

I add a patch in 2.11.0 about this issue

**Comment by rubensousa** [comment]
Thank you! I'm going to close this since 2.11.0 is already released.
