### ISSUE TITLE
StrictMode violation in 2.16.0

### ISSUE THREAD

**Issue by hameno** [at-internet/atinternet-android-sdk#26]
Database access in Core.java is not safe. All Closeable objects should always be wrapped in a try-finally or even better try-with-resources block.
Example of violation:

```java
 ArrayList<Hit> getOfflineHits() {
        SQLiteDatabase db = getReadableDatabase();
        if (db == null) {
            return new ArrayList<>();
        }
        ArrayList<Hit> hits = new ArrayList<>();
        Cursor c = db.rawQuery(SELECT_ALL_QUERY + "ORDER BY " + ID + " ASC", null);
        if (c != null && c.getCount() > 0) {
            c.moveToFirst();
            do {
                String hit = c.getString(c.getColumnIndex(HIT));
                String time = c.getString(c.getColumnIndex(DATE));
                int retry = c.getInt(c.getColumnIndex(RETRY));
                hits.add(new Hit(hit, new Date(Long.parseLong(time)), retry, true));
            }
            while (c.moveToNext());
            c.close();
        }
        db.close();
        return hits;
    }
```

Should be written like this:

```java
ArrayList<Hit> getOfflineHits() {
    SQLiteDatabase db = null;
    try {
        db = getReadableDatabase();
        if (db == null) {
            return new ArrayList<>();
        }
        ArrayList<Hit> hits = new ArrayList<>();
        Cursor c = null;
        try {
            c = db.rawQuery(SELECT_ALL_QUERY + "ORDER BY " + ID + " ASC", null);
            if (c != null && c.getCount() > 0) {
                c.moveToFirst();
                do {
                    String hit = c.getString(c.getColumnIndex(HIT));
                    String time = c.getString(c.getColumnIndex(DATE));
                    int retry = c.getInt(c.getColumnIndex(RETRY));
                    hits.add(new Hit(hit, new Date(Long.parseLong(time)), retry, true));
                }
                while (c.moveToNext());
            }
        } finally {
            if (c != null) c.close();
        }
    } finally {
        db.close();
    }
    return hits;
}
```

```
2020-05-15 14:29:54.878 D/StrictMode: StrictMode policy violation: android.os.strictmode.SqliteObjectLeakedViolation: Finalizing a Cursor that has not been deactivated or closed. database = /data/user/0/com.sprylab.purple.android.apps.trackingtest/databases/TrackerDatabase, table = null, query = SELECT * FROM StoredOfflineHit ORDER BY id ASC
        at android.os.StrictMode.onSqliteObjectLeaked(StrictMode.java:2060)
        at android.database.sqlite.SQLiteCursor.finalize(SQLiteCursor.java:289)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
        at android.database.sqlite.SQLiteCursor.<init>(SQLiteCursor.java:106)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:52)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1443)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1382)
        at com.atinternet.tracker.Storage.getOfflineHits(Core.java:2011)
        at com.atinternet.tracker.Sender.sendOfflineHits(Core.java:812)
        at com.atinternet.tracker.Sender.send(Core.java:804)
        at com.atinternet.tracker.Builder.run(Core.java:516)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by nsagnett** [comment]
Thanks for your feedback ! The fix will be integrate in next release

**Comment by nsagnett** [comment]
Hi ! 

It's ok since 2.17.0, released today 

Regards
