### ISSUE TITLE
App crashes sometimes when onResume() is called

### ISSUE THREAD

**Issue by AnneBullert** [at-internet/atinternet-android-sdk#9]
**The app crashes sometimes because of a missing Null check:**

**Debugger.java**
```
public static void setViewerVisibility(boolean visible) {
        if (bubbleImage != null) {
            bubbleVisibility = visible ? View.VISIBLE : View.GONE;
            bubbleImage.get().setVisibility(bubbleVisibility);
        }
 }
```

should be 

```
if (bubbleImage != null && bubbleImage.get() != null) {
            bubbleVisibility = visible ? View.VISIBLE : View.GONE;
            bubbleImage.get().setVisibility(bubbleVisibility);
        }
```

**Stacktrace:**
java.lang.RuntimeException: Unable to resume activity: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.atinternet.tracker.ATImageView.setVisibility(int)' on a null object reference
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3403)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3434)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5951)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.atinternet.tracker.ATImageView.setVisibility(int)' on a null object reference
at com.atinternet.tracker.Debugger.setViewerVisibility(Debugger.java:171)
at com.atinternet.tracker.TrackerActivityLifeCycle.onActivityResumed(CoreFeatures.java:452)
at android.app.Application.dispatchActivityResumed(Application.java:232)
at android.app.Activity.onResume(Activity.java:1294)
at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
at roboguice.activity.RoboActionBarActivity.onResume(RoboActionBarActivity.java:112)
at ....activities.ABaseActivity.onResume(ABaseActivity.java:179)
at ....activities.MainActivity.onResume(MainActivity.java:215)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
at android.app.Activity.performResume(Activity.java:6412)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3392)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3434) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:145) 
at android.app.ActivityThread.main(ActivityThread.java:5951) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by sonicso** [comment]
Hi, thank you for reporting this bug, a fix has just been deployed.

**Comment by houssemzaier** [comment]
Hi,
We are using the latest version "2.21.0".
But we still have the same issue 
` java.lang.NullPointerException: Attempt to invoke virtual method 'void com.atinternet.tracker.Debugger$DebuggerEventListAdapter.notifyDataSetChanged()' on a null object reference
        at com.atinternet.tracker.Sender$2.run(Core.java:835)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`
        
Clearly that is an internal problem.
